import type { Metadata } from "next";
import {
  Inter,
  Josefin_Sans,
  Geist,
  DM_Serif_Display,
  Ultra,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/app/providers";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
  weight: "400",
  variable: "--font-serif",
  subsets: ["latin"],
});

const ultra = Ultra({
  weight: "400",
  variable: "--font-ultra",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "bg-canvas",
        "antialiased",
        inter.variable,
        josefinSans.variable,
        dmSerifDisplay.variable,
        ultra.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
